als_freeze: false
blend_factor: 0.15
dropout: 0.48
embedding_dim: 300
enable_user_product_dim_reduce: false
extern_params:
  als_factors: 15
  als_iterations: 30
  als_regularization: 0.0006758197968258082
  cull_unknown_threshold: 0
  random_state: 4
filter_sizes:
- 2
- 3
- 4
- 5
- 7
latent_user_product_dim: 25
learning_rate: 0.0008
n_filters: 150
no_load_glove: false
num_products: 50052
num_users: 123957
output_dim: 5
product_emb_dim: 15
unfreeze_epoch: 0
user_emb_dim: 15
weight_decay: 5.0e-06
