als_freeze: false
blend_factor: 0.0
dropout: 0.4
embedding_dim: 300
enable_user_product_dim_reduce: false
extern_params:
  als_factors: 50
  als_iterations: 1
  als_regularization: 0.1
  cull_unknown_threshold: 0
  random_state: 4
filter_sizes:
- 3
- 4
- 5
- 7
latent_user_product_dim: 25
learning_rate: 0.001
n_filters: 100
no_load_glove: false
num_products: 50052
num_users: 123957
output_dim: 5
product_emb_dim: 50
unfreeze_epoch: 0
user_emb_dim: 50
weight_decay: null
